
namespace Minecraft_Server_Hub
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.reloadnames = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.minecraftserverhub = new Bunifu.UI.WinForms.BunifuLabel();
            this.minimize = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.close = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.server6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.mainpanel = new Bunifu.UI.WinForms.BunifuPanel();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(25)))), ((int)(((byte)(25)))));
            this.panel1.Controls.Add(this.reloadnames);
            this.panel1.Controls.Add(this.minecraftserverhub);
            this.panel1.Controls.Add(this.minimize);
            this.panel1.Controls.Add(this.close);
            this.panel1.Location = new System.Drawing.Point(-4, -5);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1200, 50);
            this.panel1.TabIndex = 0;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            this.panel1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseMove);
            // 
            // reloadnames
            // 
            this.reloadnames.AllowAnimations = true;
            this.reloadnames.AllowMouseEffects = true;
            this.reloadnames.AllowToggling = false;
            this.reloadnames.AnimationSpeed = 200;
            this.reloadnames.AutoGenerateColors = false;
            this.reloadnames.AutoRoundBorders = false;
            this.reloadnames.AutoSizeLeftIcon = true;
            this.reloadnames.AutoSizeRightIcon = true;
            this.reloadnames.BackColor = System.Drawing.Color.Transparent;
            this.reloadnames.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("reloadnames.BackgroundImage")));
            this.reloadnames.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reloadnames.ButtonText = "Reload Server Names";
            this.reloadnames.ButtonTextMarginLeft = 0;
            this.reloadnames.ColorContrastOnClick = 45;
            this.reloadnames.ColorContrastOnHover = 45;
            this.reloadnames.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.reloadnames.CustomizableEdges = borderEdges1;
            this.reloadnames.DialogResult = System.Windows.Forms.DialogResult.None;
            this.reloadnames.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reloadnames.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reloadnames.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reloadnames.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.reloadnames.Font = new System.Drawing.Font("Minecraft", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.reloadnames.ForeColor = System.Drawing.Color.White;
            this.reloadnames.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.reloadnames.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.reloadnames.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.reloadnames.IconMarginLeft = 11;
            this.reloadnames.IconPadding = 10;
            this.reloadnames.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.reloadnames.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.reloadnames.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.reloadnames.IconSize = 25;
            this.reloadnames.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.IdleBorderRadius = 1;
            this.reloadnames.IdleBorderThickness = 1;
            this.reloadnames.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.IdleIconLeftImage = null;
            this.reloadnames.IdleIconRightImage = null;
            this.reloadnames.IndicateFocus = true;
            this.reloadnames.Location = new System.Drawing.Point(925, 11);
            this.reloadnames.Name = "reloadnames";
            this.reloadnames.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.reloadnames.OnDisabledState.BorderRadius = 1;
            this.reloadnames.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reloadnames.OnDisabledState.BorderThickness = 1;
            this.reloadnames.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.reloadnames.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.reloadnames.OnDisabledState.IconLeftImage = null;
            this.reloadnames.OnDisabledState.IconRightImage = null;
            this.reloadnames.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.reloadnames.onHoverState.BorderRadius = 1;
            this.reloadnames.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reloadnames.onHoverState.BorderThickness = 1;
            this.reloadnames.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.reloadnames.onHoverState.ForeColor = System.Drawing.Color.White;
            this.reloadnames.onHoverState.IconLeftImage = null;
            this.reloadnames.onHoverState.IconRightImage = null;
            this.reloadnames.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.OnIdleState.BorderRadius = 1;
            this.reloadnames.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reloadnames.OnIdleState.BorderThickness = 1;
            this.reloadnames.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.reloadnames.OnIdleState.IconLeftImage = null;
            this.reloadnames.OnIdleState.IconRightImage = null;
            this.reloadnames.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.OnPressedState.BorderRadius = 1;
            this.reloadnames.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.reloadnames.OnPressedState.BorderThickness = 1;
            this.reloadnames.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.reloadnames.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.reloadnames.OnPressedState.IconLeftImage = null;
            this.reloadnames.OnPressedState.IconRightImage = null;
            this.reloadnames.Size = new System.Drawing.Size(193, 30);
            this.reloadnames.TabIndex = 4;
            this.reloadnames.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.reloadnames.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.reloadnames.TextMarginLeft = 0;
            this.reloadnames.TextPadding = new System.Windows.Forms.Padding(0);
            this.reloadnames.UseDefaultRadiusAndThickness = true;
            this.reloadnames.Click += new System.EventHandler(this.reloadnames_Click);
            // 
            // minecraftserverhub
            // 
            this.minecraftserverhub.AllowParentOverrides = false;
            this.minecraftserverhub.AutoEllipsis = false;
            this.minecraftserverhub.Cursor = System.Windows.Forms.Cursors.Default;
            this.minecraftserverhub.CursorType = System.Windows.Forms.Cursors.Default;
            this.minecraftserverhub.Font = new System.Drawing.Font("Minecraft", 21.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.minecraftserverhub.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.minecraftserverhub.Location = new System.Drawing.Point(11, 7);
            this.minecraftserverhub.Name = "minecraftserverhub";
            this.minecraftserverhub.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.minecraftserverhub.Size = new System.Drawing.Size(312, 35);
            this.minecraftserverhub.TabIndex = 3;
            this.minecraftserverhub.Text = "Minecraft Server Hub";
            this.minecraftserverhub.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.minecraftserverhub.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.minecraftserverhub.MouseDown += new System.Windows.Forms.MouseEventHandler(this.minecraftserverhub_MouseDown);
            this.minecraftserverhub.MouseMove += new System.Windows.Forms.MouseEventHandler(this.minecraftserverhub_MouseMove);
            // 
            // minimize
            // 
            this.minimize.AllowAnimations = true;
            this.minimize.AllowMouseEffects = true;
            this.minimize.AllowToggling = false;
            this.minimize.AnimationSpeed = 200;
            this.minimize.AutoGenerateColors = false;
            this.minimize.AutoRoundBorders = false;
            this.minimize.AutoSizeLeftIcon = true;
            this.minimize.AutoSizeRightIcon = true;
            this.minimize.BackColor = System.Drawing.Color.Transparent;
            this.minimize.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("minimize.BackgroundImage")));
            this.minimize.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.minimize.ButtonText = "-";
            this.minimize.ButtonTextMarginLeft = 0;
            this.minimize.ColorContrastOnClick = 45;
            this.minimize.ColorContrastOnHover = 45;
            this.minimize.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.minimize.CustomizableEdges = borderEdges2;
            this.minimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.minimize.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.minimize.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.minimize.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.minimize.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.minimize.Font = new System.Drawing.Font("Minecraft", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.minimize.ForeColor = System.Drawing.Color.White;
            this.minimize.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.minimize.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.minimize.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.minimize.IconMarginLeft = 11;
            this.minimize.IconPadding = 10;
            this.minimize.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.minimize.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.minimize.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.minimize.IconSize = 25;
            this.minimize.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.IdleBorderRadius = 1;
            this.minimize.IdleBorderThickness = 1;
            this.minimize.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.IdleIconLeftImage = null;
            this.minimize.IdleIconRightImage = null;
            this.minimize.IndicateFocus = true;
            this.minimize.Location = new System.Drawing.Point(1124, 11);
            this.minimize.Name = "minimize";
            this.minimize.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.minimize.OnDisabledState.BorderRadius = 1;
            this.minimize.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.minimize.OnDisabledState.BorderThickness = 1;
            this.minimize.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.minimize.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.minimize.OnDisabledState.IconLeftImage = null;
            this.minimize.OnDisabledState.IconRightImage = null;
            this.minimize.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.minimize.onHoverState.BorderRadius = 1;
            this.minimize.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.minimize.onHoverState.BorderThickness = 1;
            this.minimize.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.minimize.onHoverState.ForeColor = System.Drawing.Color.White;
            this.minimize.onHoverState.IconLeftImage = null;
            this.minimize.onHoverState.IconRightImage = null;
            this.minimize.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.OnIdleState.BorderRadius = 1;
            this.minimize.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.minimize.OnIdleState.BorderThickness = 1;
            this.minimize.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.minimize.OnIdleState.IconLeftImage = null;
            this.minimize.OnIdleState.IconRightImage = null;
            this.minimize.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.OnPressedState.BorderRadius = 1;
            this.minimize.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.minimize.OnPressedState.BorderThickness = 1;
            this.minimize.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.minimize.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.minimize.OnPressedState.IconLeftImage = null;
            this.minimize.OnPressedState.IconRightImage = null;
            this.minimize.Size = new System.Drawing.Size(30, 30);
            this.minimize.TabIndex = 2;
            this.minimize.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.minimize.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.minimize.TextMarginLeft = 0;
            this.minimize.TextPadding = new System.Windows.Forms.Padding(0);
            this.minimize.UseDefaultRadiusAndThickness = true;
            this.minimize.Click += new System.EventHandler(this.minimize_Click);
            // 
            // close
            // 
            this.close.AllowAnimations = true;
            this.close.AllowMouseEffects = true;
            this.close.AllowToggling = false;
            this.close.AnimationSpeed = 200;
            this.close.AutoGenerateColors = false;
            this.close.AutoRoundBorders = false;
            this.close.AutoSizeLeftIcon = true;
            this.close.AutoSizeRightIcon = true;
            this.close.BackColor = System.Drawing.Color.Transparent;
            this.close.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("close.BackgroundImage")));
            this.close.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.close.ButtonText = "X";
            this.close.ButtonTextMarginLeft = 0;
            this.close.ColorContrastOnClick = 45;
            this.close.ColorContrastOnHover = 45;
            this.close.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.close.CustomizableEdges = borderEdges3;
            this.close.DialogResult = System.Windows.Forms.DialogResult.None;
            this.close.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.close.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.close.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.close.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.close.Font = new System.Drawing.Font("Minecraft", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.close.ForeColor = System.Drawing.Color.White;
            this.close.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.close.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.close.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.close.IconMarginLeft = 11;
            this.close.IconPadding = 10;
            this.close.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.close.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.close.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.close.IconSize = 25;
            this.close.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.IdleBorderRadius = 1;
            this.close.IdleBorderThickness = 1;
            this.close.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.IdleIconLeftImage = null;
            this.close.IdleIconRightImage = null;
            this.close.IndicateFocus = true;
            this.close.Location = new System.Drawing.Point(1160, 11);
            this.close.Name = "close";
            this.close.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.close.OnDisabledState.BorderRadius = 1;
            this.close.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.close.OnDisabledState.BorderThickness = 1;
            this.close.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.close.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.close.OnDisabledState.IconLeftImage = null;
            this.close.OnDisabledState.IconRightImage = null;
            this.close.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.close.onHoverState.BorderRadius = 1;
            this.close.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.close.onHoverState.BorderThickness = 1;
            this.close.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.close.onHoverState.ForeColor = System.Drawing.Color.White;
            this.close.onHoverState.IconLeftImage = null;
            this.close.onHoverState.IconRightImage = null;
            this.close.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.OnIdleState.BorderRadius = 1;
            this.close.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.close.OnIdleState.BorderThickness = 1;
            this.close.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.close.OnIdleState.IconLeftImage = null;
            this.close.OnIdleState.IconRightImage = null;
            this.close.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.OnPressedState.BorderRadius = 1;
            this.close.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.close.OnPressedState.BorderThickness = 1;
            this.close.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.close.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.close.OnPressedState.IconLeftImage = null;
            this.close.OnPressedState.IconRightImage = null;
            this.close.Size = new System.Drawing.Size(30, 30);
            this.close.TabIndex = 1;
            this.close.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.close.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.close.TextMarginLeft = 0;
            this.close.TextPadding = new System.Windows.Forms.Padding(0);
            this.close.UseDefaultRadiusAndThickness = true;
            this.close.Click += new System.EventHandler(this.close_Click);
            // 
            // server1
            // 
            this.server1.AllowAnimations = true;
            this.server1.AllowMouseEffects = true;
            this.server1.AllowToggling = false;
            this.server1.AnimationSpeed = 200;
            this.server1.AutoGenerateColors = false;
            this.server1.AutoRoundBorders = false;
            this.server1.AutoSizeLeftIcon = true;
            this.server1.AutoSizeRightIcon = true;
            this.server1.BackColor = System.Drawing.Color.Transparent;
            this.server1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server1.BackgroundImage")));
            this.server1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server1.ButtonText = "";
            this.server1.ButtonTextMarginLeft = 0;
            this.server1.ColorContrastOnClick = 45;
            this.server1.ColorContrastOnHover = 45;
            this.server1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.server1.CustomizableEdges = borderEdges4;
            this.server1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server1.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server1.ForeColor = System.Drawing.Color.White;
            this.server1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server1.IconMarginLeft = 11;
            this.server1.IconPadding = 10;
            this.server1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server1.IconSize = 25;
            this.server1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.IdleBorderRadius = 1;
            this.server1.IdleBorderThickness = 1;
            this.server1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.IdleIconLeftImage = null;
            this.server1.IdleIconRightImage = null;
            this.server1.IndicateFocus = true;
            this.server1.Location = new System.Drawing.Point(56, 51);
            this.server1.Name = "server1";
            this.server1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server1.OnDisabledState.BorderRadius = 1;
            this.server1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server1.OnDisabledState.BorderThickness = 1;
            this.server1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server1.OnDisabledState.IconLeftImage = null;
            this.server1.OnDisabledState.IconRightImage = null;
            this.server1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server1.onHoverState.BorderRadius = 1;
            this.server1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server1.onHoverState.BorderThickness = 1;
            this.server1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server1.onHoverState.IconLeftImage = null;
            this.server1.onHoverState.IconRightImage = null;
            this.server1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.OnIdleState.BorderRadius = 1;
            this.server1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server1.OnIdleState.BorderThickness = 1;
            this.server1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server1.OnIdleState.IconLeftImage = null;
            this.server1.OnIdleState.IconRightImage = null;
            this.server1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.OnPressedState.BorderRadius = 1;
            this.server1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server1.OnPressedState.BorderThickness = 1;
            this.server1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server1.OnPressedState.IconLeftImage = null;
            this.server1.OnPressedState.IconRightImage = null;
            this.server1.Size = new System.Drawing.Size(175, 54);
            this.server1.TabIndex = 4;
            this.server1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server1.TextMarginLeft = 0;
            this.server1.TextPadding = new System.Windows.Forms.Padding(0);
            this.server1.UseDefaultRadiusAndThickness = true;
            this.server1.Click += new System.EventHandler(this.server1_Click);
            // 
            // server2
            // 
            this.server2.AllowAnimations = true;
            this.server2.AllowMouseEffects = true;
            this.server2.AllowToggling = false;
            this.server2.AnimationSpeed = 200;
            this.server2.AutoGenerateColors = false;
            this.server2.AutoRoundBorders = false;
            this.server2.AutoSizeLeftIcon = true;
            this.server2.AutoSizeRightIcon = true;
            this.server2.BackColor = System.Drawing.Color.Transparent;
            this.server2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server2.BackgroundImage")));
            this.server2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server2.ButtonText = "";
            this.server2.ButtonTextMarginLeft = 0;
            this.server2.ColorContrastOnClick = 45;
            this.server2.ColorContrastOnHover = 45;
            this.server2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.server2.CustomizableEdges = borderEdges5;
            this.server2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server2.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server2.ForeColor = System.Drawing.Color.White;
            this.server2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server2.IconMarginLeft = 11;
            this.server2.IconPadding = 10;
            this.server2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server2.IconSize = 25;
            this.server2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.IdleBorderRadius = 1;
            this.server2.IdleBorderThickness = 1;
            this.server2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.IdleIconLeftImage = null;
            this.server2.IdleIconRightImage = null;
            this.server2.IndicateFocus = true;
            this.server2.Location = new System.Drawing.Point(237, 51);
            this.server2.Name = "server2";
            this.server2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server2.OnDisabledState.BorderRadius = 1;
            this.server2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server2.OnDisabledState.BorderThickness = 1;
            this.server2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server2.OnDisabledState.IconLeftImage = null;
            this.server2.OnDisabledState.IconRightImage = null;
            this.server2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server2.onHoverState.BorderRadius = 1;
            this.server2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server2.onHoverState.BorderThickness = 1;
            this.server2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server2.onHoverState.IconLeftImage = null;
            this.server2.onHoverState.IconRightImage = null;
            this.server2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.OnIdleState.BorderRadius = 1;
            this.server2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server2.OnIdleState.BorderThickness = 1;
            this.server2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server2.OnIdleState.IconLeftImage = null;
            this.server2.OnIdleState.IconRightImage = null;
            this.server2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.OnPressedState.BorderRadius = 1;
            this.server2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server2.OnPressedState.BorderThickness = 1;
            this.server2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server2.OnPressedState.IconLeftImage = null;
            this.server2.OnPressedState.IconRightImage = null;
            this.server2.Size = new System.Drawing.Size(175, 54);
            this.server2.TabIndex = 5;
            this.server2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server2.TextMarginLeft = 0;
            this.server2.TextPadding = new System.Windows.Forms.Padding(0);
            this.server2.UseDefaultRadiusAndThickness = true;
            // 
            // server3
            // 
            this.server3.AllowAnimations = true;
            this.server3.AllowMouseEffects = true;
            this.server3.AllowToggling = false;
            this.server3.AnimationSpeed = 200;
            this.server3.AutoGenerateColors = false;
            this.server3.AutoRoundBorders = false;
            this.server3.AutoSizeLeftIcon = true;
            this.server3.AutoSizeRightIcon = true;
            this.server3.BackColor = System.Drawing.Color.Transparent;
            this.server3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server3.BackgroundImage")));
            this.server3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server3.ButtonText = "";
            this.server3.ButtonTextMarginLeft = 0;
            this.server3.ColorContrastOnClick = 45;
            this.server3.ColorContrastOnHover = 45;
            this.server3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.server3.CustomizableEdges = borderEdges6;
            this.server3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server3.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server3.ForeColor = System.Drawing.Color.White;
            this.server3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server3.IconMarginLeft = 11;
            this.server3.IconPadding = 10;
            this.server3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server3.IconSize = 25;
            this.server3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.IdleBorderRadius = 1;
            this.server3.IdleBorderThickness = 1;
            this.server3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.IdleIconLeftImage = null;
            this.server3.IdleIconRightImage = null;
            this.server3.IndicateFocus = true;
            this.server3.Location = new System.Drawing.Point(418, 51);
            this.server3.Name = "server3";
            this.server3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server3.OnDisabledState.BorderRadius = 1;
            this.server3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server3.OnDisabledState.BorderThickness = 1;
            this.server3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server3.OnDisabledState.IconLeftImage = null;
            this.server3.OnDisabledState.IconRightImage = null;
            this.server3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server3.onHoverState.BorderRadius = 1;
            this.server3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server3.onHoverState.BorderThickness = 1;
            this.server3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server3.onHoverState.IconLeftImage = null;
            this.server3.onHoverState.IconRightImage = null;
            this.server3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.OnIdleState.BorderRadius = 1;
            this.server3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server3.OnIdleState.BorderThickness = 1;
            this.server3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server3.OnIdleState.IconLeftImage = null;
            this.server3.OnIdleState.IconRightImage = null;
            this.server3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.OnPressedState.BorderRadius = 1;
            this.server3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server3.OnPressedState.BorderThickness = 1;
            this.server3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server3.OnPressedState.IconLeftImage = null;
            this.server3.OnPressedState.IconRightImage = null;
            this.server3.Size = new System.Drawing.Size(175, 54);
            this.server3.TabIndex = 6;
            this.server3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server3.TextMarginLeft = 0;
            this.server3.TextPadding = new System.Windows.Forms.Padding(0);
            this.server3.UseDefaultRadiusAndThickness = true;
            // 
            // server4
            // 
            this.server4.AllowAnimations = true;
            this.server4.AllowMouseEffects = true;
            this.server4.AllowToggling = false;
            this.server4.AnimationSpeed = 200;
            this.server4.AutoGenerateColors = false;
            this.server4.AutoRoundBorders = false;
            this.server4.AutoSizeLeftIcon = true;
            this.server4.AutoSizeRightIcon = true;
            this.server4.BackColor = System.Drawing.Color.Transparent;
            this.server4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server4.BackgroundImage")));
            this.server4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server4.ButtonText = "";
            this.server4.ButtonTextMarginLeft = 0;
            this.server4.ColorContrastOnClick = 45;
            this.server4.ColorContrastOnHover = 45;
            this.server4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.server4.CustomizableEdges = borderEdges7;
            this.server4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server4.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server4.ForeColor = System.Drawing.Color.White;
            this.server4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server4.IconMarginLeft = 11;
            this.server4.IconPadding = 10;
            this.server4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server4.IconSize = 25;
            this.server4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.IdleBorderRadius = 1;
            this.server4.IdleBorderThickness = 1;
            this.server4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.IdleIconLeftImage = null;
            this.server4.IdleIconRightImage = null;
            this.server4.IndicateFocus = true;
            this.server4.Location = new System.Drawing.Point(599, 51);
            this.server4.Name = "server4";
            this.server4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server4.OnDisabledState.BorderRadius = 1;
            this.server4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server4.OnDisabledState.BorderThickness = 1;
            this.server4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server4.OnDisabledState.IconLeftImage = null;
            this.server4.OnDisabledState.IconRightImage = null;
            this.server4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server4.onHoverState.BorderRadius = 1;
            this.server4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server4.onHoverState.BorderThickness = 1;
            this.server4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server4.onHoverState.IconLeftImage = null;
            this.server4.onHoverState.IconRightImage = null;
            this.server4.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.OnIdleState.BorderRadius = 1;
            this.server4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server4.OnIdleState.BorderThickness = 1;
            this.server4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server4.OnIdleState.IconLeftImage = null;
            this.server4.OnIdleState.IconRightImage = null;
            this.server4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.OnPressedState.BorderRadius = 1;
            this.server4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server4.OnPressedState.BorderThickness = 1;
            this.server4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server4.OnPressedState.IconLeftImage = null;
            this.server4.OnPressedState.IconRightImage = null;
            this.server4.Size = new System.Drawing.Size(175, 54);
            this.server4.TabIndex = 7;
            this.server4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server4.TextMarginLeft = 0;
            this.server4.TextPadding = new System.Windows.Forms.Padding(0);
            this.server4.UseDefaultRadiusAndThickness = true;
            // 
            // server5
            // 
            this.server5.AllowAnimations = true;
            this.server5.AllowMouseEffects = true;
            this.server5.AllowToggling = false;
            this.server5.AnimationSpeed = 200;
            this.server5.AutoGenerateColors = false;
            this.server5.AutoRoundBorders = false;
            this.server5.AutoSizeLeftIcon = true;
            this.server5.AutoSizeRightIcon = true;
            this.server5.BackColor = System.Drawing.Color.Transparent;
            this.server5.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server5.BackgroundImage")));
            this.server5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server5.ButtonText = "";
            this.server5.ButtonTextMarginLeft = 0;
            this.server5.ColorContrastOnClick = 45;
            this.server5.ColorContrastOnHover = 45;
            this.server5.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.server5.CustomizableEdges = borderEdges8;
            this.server5.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server5.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server5.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server5.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server5.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server5.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server5.ForeColor = System.Drawing.Color.White;
            this.server5.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server5.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server5.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server5.IconMarginLeft = 11;
            this.server5.IconPadding = 10;
            this.server5.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server5.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server5.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server5.IconSize = 25;
            this.server5.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.IdleBorderRadius = 1;
            this.server5.IdleBorderThickness = 1;
            this.server5.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.IdleIconLeftImage = null;
            this.server5.IdleIconRightImage = null;
            this.server5.IndicateFocus = true;
            this.server5.Location = new System.Drawing.Point(780, 51);
            this.server5.Name = "server5";
            this.server5.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server5.OnDisabledState.BorderRadius = 1;
            this.server5.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server5.OnDisabledState.BorderThickness = 1;
            this.server5.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server5.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server5.OnDisabledState.IconLeftImage = null;
            this.server5.OnDisabledState.IconRightImage = null;
            this.server5.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server5.onHoverState.BorderRadius = 1;
            this.server5.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server5.onHoverState.BorderThickness = 1;
            this.server5.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server5.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server5.onHoverState.IconLeftImage = null;
            this.server5.onHoverState.IconRightImage = null;
            this.server5.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.OnIdleState.BorderRadius = 1;
            this.server5.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server5.OnIdleState.BorderThickness = 1;
            this.server5.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server5.OnIdleState.IconLeftImage = null;
            this.server5.OnIdleState.IconRightImage = null;
            this.server5.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.OnPressedState.BorderRadius = 1;
            this.server5.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server5.OnPressedState.BorderThickness = 1;
            this.server5.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server5.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server5.OnPressedState.IconLeftImage = null;
            this.server5.OnPressedState.IconRightImage = null;
            this.server5.Size = new System.Drawing.Size(175, 54);
            this.server5.TabIndex = 8;
            this.server5.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server5.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server5.TextMarginLeft = 0;
            this.server5.TextPadding = new System.Windows.Forms.Padding(0);
            this.server5.UseDefaultRadiusAndThickness = true;
            // 
            // server6
            // 
            this.server6.AllowAnimations = true;
            this.server6.AllowMouseEffects = true;
            this.server6.AllowToggling = false;
            this.server6.AnimationSpeed = 200;
            this.server6.AutoGenerateColors = false;
            this.server6.AutoRoundBorders = false;
            this.server6.AutoSizeLeftIcon = true;
            this.server6.AutoSizeRightIcon = true;
            this.server6.BackColor = System.Drawing.Color.Transparent;
            this.server6.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("server6.BackgroundImage")));
            this.server6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server6.ButtonText = "";
            this.server6.ButtonTextMarginLeft = 0;
            this.server6.ColorContrastOnClick = 45;
            this.server6.ColorContrastOnHover = 45;
            this.server6.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.server6.CustomizableEdges = borderEdges9;
            this.server6.DialogResult = System.Windows.Forms.DialogResult.None;
            this.server6.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server6.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server6.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server6.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.server6.Font = new System.Drawing.Font("Minecraft", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.server6.ForeColor = System.Drawing.Color.White;
            this.server6.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.server6.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.server6.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.server6.IconMarginLeft = 11;
            this.server6.IconPadding = 10;
            this.server6.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.server6.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.server6.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.server6.IconSize = 25;
            this.server6.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.IdleBorderRadius = 1;
            this.server6.IdleBorderThickness = 1;
            this.server6.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.IdleIconLeftImage = null;
            this.server6.IdleIconRightImage = null;
            this.server6.IndicateFocus = true;
            this.server6.Location = new System.Drawing.Point(961, 51);
            this.server6.Name = "server6";
            this.server6.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.server6.OnDisabledState.BorderRadius = 1;
            this.server6.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server6.OnDisabledState.BorderThickness = 1;
            this.server6.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.server6.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.server6.OnDisabledState.IconLeftImage = null;
            this.server6.OnDisabledState.IconRightImage = null;
            this.server6.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server6.onHoverState.BorderRadius = 1;
            this.server6.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server6.onHoverState.BorderThickness = 1;
            this.server6.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(71)))), ((int)(((byte)(122)))), ((int)(((byte)(30)))));
            this.server6.onHoverState.ForeColor = System.Drawing.Color.White;
            this.server6.onHoverState.IconLeftImage = null;
            this.server6.onHoverState.IconRightImage = null;
            this.server6.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.OnIdleState.BorderRadius = 1;
            this.server6.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server6.OnIdleState.BorderThickness = 1;
            this.server6.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.server6.OnIdleState.IconLeftImage = null;
            this.server6.OnIdleState.IconRightImage = null;
            this.server6.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.OnPressedState.BorderRadius = 1;
            this.server6.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.server6.OnPressedState.BorderThickness = 1;
            this.server6.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(112)))), ((int)(((byte)(178)))), ((int)(((byte)(55)))));
            this.server6.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.server6.OnPressedState.IconLeftImage = null;
            this.server6.OnPressedState.IconRightImage = null;
            this.server6.Size = new System.Drawing.Size(175, 54);
            this.server6.TabIndex = 9;
            this.server6.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.server6.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.server6.TextMarginLeft = 0;
            this.server6.TextPadding = new System.Windows.Forms.Padding(0);
            this.server6.UseDefaultRadiusAndThickness = true;
            // 
            // mainpanel
            // 
            this.mainpanel.BackgroundColor = System.Drawing.Color.Transparent;
            this.mainpanel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("mainpanel.BackgroundImage")));
            this.mainpanel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.mainpanel.BorderColor = System.Drawing.Color.Transparent;
            this.mainpanel.BorderRadius = 3;
            this.mainpanel.BorderThickness = 1;
            this.mainpanel.Location = new System.Drawing.Point(7, 111);
            this.mainpanel.Name = "mainpanel";
            this.mainpanel.ShowBorders = true;
            this.mainpanel.Size = new System.Drawing.Size(1179, 603);
            this.mainpanel.TabIndex = 10;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(35)))), ((int)(((byte)(35)))), ((int)(((byte)(35)))));
            this.ClientSize = new System.Drawing.Size(1193, 726);
            this.Controls.Add(this.mainpanel);
            this.Controls.Add(this.server6);
            this.Controls.Add(this.server5);
            this.Controls.Add(this.server4);
            this.Controls.Add(this.server3);
            this.Controls.Add(this.server2);
            this.Controls.Add(this.server1);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Form1";
            this.Text = "Minecraft Server Hub";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton close;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton minimize;
        private Bunifu.UI.WinForms.BunifuLabel minecraftserverhub;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton server6;
        private Bunifu.UI.WinForms.BunifuPanel mainpanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton reloadnames;
    }
}

